--------------------------------------------------------
--  Fichier cr�� - mardi-janvier-26-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table T_REPORT
--------------------------------------------------------

  CREATE TABLE "TOPPATO"."T_REPORT" 
   (	"ID" NUMBER(*,0), 
	"SPRINT_ID" NUMBER(*,0), 
	"TITLE" VARCHAR2(255 BYTE), 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"TEXT" VARCHAR2(255 BYTE), 
	"TYPE" VARCHAR2(255 BYTE), 
	"CREATION_DATE" DATE, 
	"UPDATE_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_CHART
--------------------------------------------------------

  CREATE TABLE "TOPPATO"."T_CHART" 
   (	"ID" NUMBER(*,0), 
	"REPORT_ID" NUMBER(*,0), 
	"TITLE" VARCHAR2(255 BYTE), 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"CHART_PATH" VARCHAR2(255 BYTE), 
	"TEXT" VARCHAR2(255 BYTE), 
	"TYPE" VARCHAR2(255 BYTE), 
	"CREATION_DATE" DATE, 
	"UPDATE_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_BACKLOG
--------------------------------------------------------

  CREATE TABLE "TOPPATO"."T_BACKLOG" 
   (	"ID" NUMBER(*,0), 
	"TITLE" VARCHAR2(255 BYTE), 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"STATUS" VARCHAR2(255 BYTE), 
	"CREATION_DATE" DATE, 
	"UPDATE_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_TEAM
--------------------------------------------------------

  CREATE TABLE "TOPPATO"."T_TEAM" 
   (	"ID" NUMBER(*,0), 
	"NAME" VARCHAR2(255 BYTE), 
	"STATUS" VARCHAR2(255 BYTE), 
	"CREATION_DATE" DATE, 
	"UPDATE_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_ATTACHEMENT
--------------------------------------------------------

  CREATE TABLE "TOPPATO"."T_ATTACHEMENT" 
   (	"ID" NUMBER(*,0), 
	"STORY_ID" NUMBER(*,0), 
	"TITLE" VARCHAR2(255 BYTE), 
	"DATA" BLOB, 
	"CREATION_DATE" DATE, 
	"UPDATE_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("DATA") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table T_PROJECT
--------------------------------------------------------

  CREATE TABLE "TOPPATO"."T_PROJECT" 
   (	"ID" NUMBER(*,0), 
	"NAME" VARCHAR2(255 BYTE), 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"STATUS" VARCHAR2(255 BYTE), 
	"CREATION_DATE" DATE, 
	"UPDATE_DATE" DATE, 
	"END_DATE" DATE, 
	"BACKLOG_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_STORY
--------------------------------------------------------

  CREATE TABLE "TOPPATO"."T_STORY" 
   (	"ID" NUMBER(*,0), 
	"REPORTER_ID" NUMBER(*,0), 
	"SPRINT_ID" NUMBER(*,0), 
	"BACKLOG_ID" NUMBER(*,0), 
	"ASSIGNED_USER_ID" NUMBER(*,0), 
	"TITLE" VARCHAR2(255 BYTE), 
	"DESCRIPTION" VARCHAR2(3000 BYTE), 
	"TYPE" VARCHAR2(50 BYTE), 
	"STATUS" VARCHAR2(50 BYTE), 
	"WORKFLOW" VARCHAR2(255 BYTE), 
	"APPLI_VERSION" VARCHAR2(50 BYTE), 
	"PRIORITY" VARCHAR2(50 BYTE), 
	"BUSINESS_VALUE" NUMBER(10,0), 
	"STORY_POINTS" NUMBER(10,0), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"ESTIMATED_END_DATE" DATE, 
	"CREATION_DATE" DATE, 
	"UPDATE_DATE" DATE, 
	"ASSIGNED_TEAM_ID" NUMBER, 
	"PROJECT_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_DAILYMEETING
--------------------------------------------------------

  CREATE TABLE "TOPPATO"."T_DAILYMEETING" 
   (	"ID" NUMBER(*,0), 
	"TITLE" VARCHAR2(255 BYTE), 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"STATUS" VARCHAR2(255 BYTE), 
	"CREATION_DATE" DATE, 
	"UPDATE_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_USER
--------------------------------------------------------

  CREATE TABLE "TOPPATO"."T_USER" 
   (	"ID" NUMBER(*,0), 
	"TEAM_ID" NUMBER(*,0), 
	"FIRSTNAME" VARCHAR2(255 BYTE), 
	"LASTNAME" VARCHAR2(255 BYTE), 
	"USERNAME" VARCHAR2(255 BYTE), 
	"PASSWORD" VARCHAR2(255 BYTE), 
	"ROLE" VARCHAR2(255 BYTE), 
	"STATUS" VARCHAR2(255 BYTE), 
	"CREATION_DATE" DATE, 
	"UPDATE_DATE" DATE, 
	"PROJECT_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_SPRINT
--------------------------------------------------------

  CREATE TABLE "TOPPATO"."T_SPRINT" 
   (	"ID" NUMBER(*,0), 
	"REPORTER_ID" NUMBER(*,0), 
	"PROJECT_ID" NUMBER(*,0), 
	"TITLE" VARCHAR2(255 BYTE), 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"STATUS" VARCHAR2(255 BYTE), 
	"WORKFLOW" VARCHAR2(255 BYTE), 
	"APPLI_VERSION" VARCHAR2(255 BYTE), 
	"BUSINESS_VALUE" NUMBER(10,0), 
	"STORY_POINTS" NUMBER(10,0), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"ESTIMATED_END_DATE" DATE, 
	"CREATION_DATE" DATE, 
	"UPDATE_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into TOPPATO.T_REPORT
SET DEFINE OFF;
REM INSERTING into TOPPATO.T_CHART
SET DEFINE OFF;
REM INSERTING into TOPPATO.T_BACKLOG
SET DEFINE OFF;
Insert into TOPPATO.T_BACKLOG (ID,TITLE,DESCRIPTION,STATUS,CREATION_DATE,UPDATE_DATE) values ('100','Backlog LIFE','Backlog du projet LIFE','ACTIVE',to_date('17/12/20','DD/MM/RR'),to_date('17/12/20','DD/MM/RR'));
Insert into TOPPATO.T_BACKLOG (ID,TITLE,DESCRIPTION,STATUS,CREATION_DATE,UPDATE_DATE) values ('105','Backlog VASCO','Backlog du projet VASCO','ACTIVE',to_date('17/12/20','DD/MM/RR'),to_date('17/12/20','DD/MM/RR'));
REM INSERTING into TOPPATO.T_TEAM
SET DEFINE OFF;
Insert into TOPPATO.T_TEAM (ID,NAME,STATUS,CREATION_DATE,UPDATE_DATE) values ('100','Master Data Management','ACTIVE',to_date('17/12/20','DD/MM/RR'),null);
Insert into TOPPATO.T_TEAM (ID,NAME,STATUS,CREATION_DATE,UPDATE_DATE) values ('105','Legal Entities Management','ACTIVE',to_date('17/12/20','DD/MM/RR'),null);
Insert into TOPPATO.T_TEAM (ID,NAME,STATUS,CREATION_DATE,UPDATE_DATE) values ('110','Securities Management','ACTIVE',to_date('17/12/20','DD/MM/RR'),null);
REM INSERTING into TOPPATO.T_ATTACHEMENT
SET DEFINE OFF;
REM INSERTING into TOPPATO.T_PROJECT
SET DEFINE OFF;
Insert into TOPPATO.T_PROJECT (ID,NAME,DESCRIPTION,STATUS,CREATION_DATE,UPDATE_DATE,END_DATE,BACKLOG_ID) values ('100','LIFE','An innovative Project','ACTIVE',to_date('17/12/20','DD/MM/RR'),to_date('17/12/20','DD/MM/RR'),null,'100');
Insert into TOPPATO.T_PROJECT (ID,NAME,DESCRIPTION,STATUS,CREATION_DATE,UPDATE_DATE,END_DATE,BACKLOG_ID) values ('105','VASCO','An Project for networking','ACTIVE',to_date('17/12/20','DD/MM/RR'),to_date('17/12/20','DD/MM/RR'),null,'105');
REM INSERTING into TOPPATO.T_STORY
SET DEFINE OFF;
Insert into TOPPATO.T_STORY (ID,REPORTER_ID,SPRINT_ID,BACKLOG_ID,ASSIGNED_USER_ID,TITLE,DESCRIPTION,TYPE,STATUS,WORKFLOW,APPLI_VERSION,PRIORITY,BUSINESS_VALUE,STORY_POINTS,START_DATE,END_DATE,ESTIMATED_END_DATE,CREATION_DATE,UPDATE_DATE,ASSIGNED_TEAM_ID,PROJECT_ID) values ('100','110','100',null,'105','Init items','Init items for search','BUG','IN_PROGRESS','CREATED',null,'MINOR',null,null,to_date('17/12/20','DD/MM/RR'),null,null,to_date('16/12/20','DD/MM/RR'),to_date('17/12/20','DD/MM/RR'),null,'100');
Insert into TOPPATO.T_STORY (ID,REPORTER_ID,SPRINT_ID,BACKLOG_ID,ASSIGNED_USER_ID,TITLE,DESCRIPTION,TYPE,STATUS,WORKFLOW,APPLI_VERSION,PRIORITY,BUSINESS_VALUE,STORY_POINTS,START_DATE,END_DATE,ESTIMATED_END_DATE,CREATION_DATE,UPDATE_DATE,ASSIGNED_TEAM_ID,PROJECT_ID) values ('105','105','105',null,'105','Create items','Create items for search','USER_STORY','IN_PROGRESS','CREATED',null,'BLOCKED',null,null,to_date('17/12/20','DD/MM/RR'),null,null,to_date('16/12/20','DD/MM/RR'),to_date('17/12/20','DD/MM/RR'),null,'100');
Insert into TOPPATO.T_STORY (ID,REPORTER_ID,SPRINT_ID,BACKLOG_ID,ASSIGNED_USER_ID,TITLE,DESCRIPTION,TYPE,STATUS,WORKFLOW,APPLI_VERSION,PRIORITY,BUSINESS_VALUE,STORY_POINTS,START_DATE,END_DATE,ESTIMATED_END_DATE,CREATION_DATE,UPDATE_DATE,ASSIGNED_TEAM_ID,PROJECT_ID) values ('115','110','110',null,'100','Delete items','Delete items for search','USER_STORY','DONE','CREATED',null,'MAJOR',null,null,to_date('17/12/20','DD/MM/RR'),null,null,to_date('16/12/20','DD/MM/RR'),to_date('17/12/20','DD/MM/RR'),null,'105');
Insert into TOPPATO.T_STORY (ID,REPORTER_ID,SPRINT_ID,BACKLOG_ID,ASSIGNED_USER_ID,TITLE,DESCRIPTION,TYPE,STATUS,WORKFLOW,APPLI_VERSION,PRIORITY,BUSINESS_VALUE,STORY_POINTS,START_DATE,END_DATE,ESTIMATED_END_DATE,CREATION_DATE,UPDATE_DATE,ASSIGNED_TEAM_ID,PROJECT_ID) values ('120','120','105',null,'115','Test 1','It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.','USER_STORY','DONE','CREATED',null,'CRITICAL',null,null,to_date('17/12/20','DD/MM/RR'),null,null,to_date('16/12/20','DD/MM/RR'),to_date('17/12/20','DD/MM/RR'),null,'105');
Insert into TOPPATO.T_STORY (ID,REPORTER_ID,SPRINT_ID,BACKLOG_ID,ASSIGNED_USER_ID,TITLE,DESCRIPTION,TYPE,STATUS,WORKFLOW,APPLI_VERSION,PRIORITY,BUSINESS_VALUE,STORY_POINTS,START_DATE,END_DATE,ESTIMATED_END_DATE,CREATION_DATE,UPDATE_DATE,ASSIGNED_TEAM_ID,PROJECT_ID) values ('125','110',null,'100',null,'Test 2','There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don''t look even slightly believable. ','BUG','IN_PROGRESS','CREATED',null,'CRITICAL',null,null,to_date('17/12/20','DD/MM/RR'),null,null,to_date('16/12/20','DD/MM/RR'),to_date('17/12/20','DD/MM/RR'),null,'100');
Insert into TOPPATO.T_STORY (ID,REPORTER_ID,SPRINT_ID,BACKLOG_ID,ASSIGNED_USER_ID,TITLE,DESCRIPTION,TYPE,STATUS,WORKFLOW,APPLI_VERSION,PRIORITY,BUSINESS_VALUE,STORY_POINTS,START_DATE,END_DATE,ESTIMATED_END_DATE,CREATION_DATE,UPDATE_DATE,ASSIGNED_TEAM_ID,PROJECT_ID) values ('130','115',null,'100','105','Test 3','Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.','BUG','IN_PROGRESS','CREATED',null,'CRITICAL',null,null,to_date('17/12/20','DD/MM/RR'),null,null,to_date('16/12/20','DD/MM/RR'),to_date('17/12/20','DD/MM/RR'),null,'100');
Insert into TOPPATO.T_STORY (ID,REPORTER_ID,SPRINT_ID,BACKLOG_ID,ASSIGNED_USER_ID,TITLE,DESCRIPTION,TYPE,STATUS,WORKFLOW,APPLI_VERSION,PRIORITY,BUSINESS_VALUE,STORY_POINTS,START_DATE,END_DATE,ESTIMATED_END_DATE,CREATION_DATE,UPDATE_DATE,ASSIGNED_TEAM_ID,PROJECT_ID) values ('135','110','105',null,'100','Test 4','The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested.','USER_STORY','TODO','CREATED',null,'UNDEFINED',null,null,to_date('17/12/20','DD/MM/RR'),null,null,to_date('16/12/20','DD/MM/RR'),to_date('17/12/20','DD/MM/RR'),null,'100');
Insert into TOPPATO.T_STORY (ID,REPORTER_ID,SPRINT_ID,BACKLOG_ID,ASSIGNED_USER_ID,TITLE,DESCRIPTION,TYPE,STATUS,WORKFLOW,APPLI_VERSION,PRIORITY,BUSINESS_VALUE,STORY_POINTS,START_DATE,END_DATE,ESTIMATED_END_DATE,CREATION_DATE,UPDATE_DATE,ASSIGNED_TEAM_ID,PROJECT_ID) values ('140','100','105',null,'120','Test 5','But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness.','BUG','BLOCKED','CREATED',null,'MAJOR',null,null,to_date('17/12/20','DD/MM/RR'),null,null,to_date('16/12/20','DD/MM/RR'),to_date('17/12/20','DD/MM/RR'),null,'100');
REM INSERTING into TOPPATO.T_DAILYMEETING
SET DEFINE OFF;
REM INSERTING into TOPPATO.T_USER
SET DEFINE OFF;
Insert into TOPPATO.T_USER (ID,TEAM_ID,FIRSTNAME,LASTNAME,USERNAME,PASSWORD,ROLE,STATUS,CREATION_DATE,UPDATE_DATE,PROJECT_ID) values ('100','100','Jean-Pierre','Dupont','dupont','1234567','USER','ACTIVE',null,null,'105');
Insert into TOPPATO.T_USER (ID,TEAM_ID,FIRSTNAME,LASTNAME,USERNAME,PASSWORD,ROLE,STATUS,CREATION_DATE,UPDATE_DATE,PROJECT_ID) values ('105','100','Paul','Lanus','paul','test','USER','ACTIVE',null,null,'105');
Insert into TOPPATO.T_USER (ID,TEAM_ID,FIRSTNAME,LASTNAME,USERNAME,PASSWORD,ROLE,STATUS,CREATION_DATE,UPDATE_DATE,PROJECT_ID) values ('110','100','Mohamed','Fofana','test','$2a$10$Nty.BIFnlKQtLtuWxoT0R.eOqYIyIL3Jfbr2PUEfvuQ5cuwLXr13O','ADMIN','ACTIVE',null,null,'100');
Insert into TOPPATO.T_USER (ID,TEAM_ID,FIRSTNAME,LASTNAME,USERNAME,PASSWORD,ROLE,STATUS,CREATION_DATE,UPDATE_DATE,PROJECT_ID) values ('115','100','Gregory','Niel','manager','$2a$10$v2O/1IeBRwK9LxSScqWGI.HrphLp/riFFmjFzmfdHiwoksSHkNHN6','MANAGER','ACTIVE',null,null,'100');
Insert into TOPPATO.T_USER (ID,TEAM_ID,FIRSTNAME,LASTNAME,USERNAME,PASSWORD,ROLE,STATUS,CREATION_DATE,UPDATE_DATE,PROJECT_ID) values ('120','100','Eric','Wagner','powner','$2a$10$bJ4q5jh6tBMXkcF4c8lzkuo4R4das/IhvyKlIroHQIaOYfKp8t8gW','PO','ACTIVE',null,null,'100');
REM INSERTING into TOPPATO.T_SPRINT
SET DEFINE OFF;
Insert into TOPPATO.T_SPRINT (ID,REPORTER_ID,PROJECT_ID,TITLE,DESCRIPTION,STATUS,WORKFLOW,APPLI_VERSION,BUSINESS_VALUE,STORY_POINTS,START_DATE,END_DATE,ESTIMATED_END_DATE,CREATION_DATE,UPDATE_DATE) values ('100','100','100','Sprint 0','Developping Search module','CLOSED','CLOSED',null,null,null,to_date('17/12/20','DD/MM/RR'),to_date('20/12/20','DD/MM/RR'),to_date('20/12/20','DD/MM/RR'),to_date('14/10/20','DD/MM/RR'),to_date('17/12/20','DD/MM/RR'));
Insert into TOPPATO.T_SPRINT (ID,REPORTER_ID,PROJECT_ID,TITLE,DESCRIPTION,STATUS,WORKFLOW,APPLI_VERSION,BUSINESS_VALUE,STORY_POINTS,START_DATE,END_DATE,ESTIMATED_END_DATE,CREATION_DATE,UPDATE_DATE) values ('105','105','100','Sprint 1','Developping Test module','RUNNING','RUNNING',null,null,null,to_date('18/12/20','DD/MM/RR'),null,null,to_date('17/12/20','DD/MM/RR'),to_date('17/12/20','DD/MM/RR'));
Insert into TOPPATO.T_SPRINT (ID,REPORTER_ID,PROJECT_ID,TITLE,DESCRIPTION,STATUS,WORKFLOW,APPLI_VERSION,BUSINESS_VALUE,STORY_POINTS,START_DATE,END_DATE,ESTIMATED_END_DATE,CREATION_DATE,UPDATE_DATE) values ('110','100','105','Sprint W','Developping Shared module','RUNNING','RUNNING',null,null,null,to_date('30/12/20','DD/MM/RR'),null,null,to_date('17/12/20','DD/MM/RR'),to_date('17/12/20','DD/MM/RR'));
--------------------------------------------------------
--  DDL for Index PK_REPORT
--------------------------------------------------------

  CREATE UNIQUE INDEX "TOPPATO"."PK_REPORT" ON "TOPPATO"."T_REPORT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_CHART
--------------------------------------------------------

  CREATE UNIQUE INDEX "TOPPATO"."PK_CHART" ON "TOPPATO"."T_CHART" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_BACKLOG
--------------------------------------------------------

  CREATE UNIQUE INDEX "TOPPATO"."PK_BACKLOG" ON "TOPPATO"."T_BACKLOG" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_TEAM
--------------------------------------------------------

  CREATE UNIQUE INDEX "TOPPATO"."PK_TEAM" ON "TOPPATO"."T_TEAM" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ATTACHEMENT
--------------------------------------------------------

  CREATE UNIQUE INDEX "TOPPATO"."PK_ATTACHEMENT" ON "TOPPATO"."T_ATTACHEMENT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_PROJECT
--------------------------------------------------------

  CREATE UNIQUE INDEX "TOPPATO"."PK_PROJECT" ON "TOPPATO"."T_PROJECT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_STORY
--------------------------------------------------------

  CREATE UNIQUE INDEX "TOPPATO"."PK_STORY" ON "TOPPATO"."T_STORY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_DAILYMEETING
--------------------------------------------------------

  CREATE UNIQUE INDEX "TOPPATO"."PK_DAILYMEETING" ON "TOPPATO"."T_DAILYMEETING" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_USER
--------------------------------------------------------

  CREATE UNIQUE INDEX "TOPPATO"."PK_USER" ON "TOPPATO"."T_USER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_SPRINT
--------------------------------------------------------

  CREATE UNIQUE INDEX "TOPPATO"."PK_SPRINT" ON "TOPPATO"."T_SPRINT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table T_REPORT
--------------------------------------------------------

  ALTER TABLE "TOPPATO"."T_REPORT" ADD CONSTRAINT "PK_REPORT" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "TOPPATO"."T_REPORT" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "TOPPATO"."T_REPORT" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "TOPPATO"."T_REPORT" MODIFY ("SPRINT_ID" NOT NULL ENABLE);
  ALTER TABLE "TOPPATO"."T_REPORT" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_CHART
--------------------------------------------------------

  ALTER TABLE "TOPPATO"."T_CHART" ADD CONSTRAINT "PK_CHART" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "TOPPATO"."T_CHART" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "TOPPATO"."T_CHART" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "TOPPATO"."T_CHART" MODIFY ("REPORT_ID" NOT NULL ENABLE);
  ALTER TABLE "TOPPATO"."T_CHART" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_BACKLOG
--------------------------------------------------------

  ALTER TABLE "TOPPATO"."T_BACKLOG" ADD CONSTRAINT "PK_BACKLOG" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "TOPPATO"."T_BACKLOG" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "TOPPATO"."T_BACKLOG" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "TOPPATO"."T_BACKLOG" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_TEAM
--------------------------------------------------------

  ALTER TABLE "TOPPATO"."T_TEAM" ADD CONSTRAINT "PK_TEAM" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "TOPPATO"."T_TEAM" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "TOPPATO"."T_TEAM" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_ATTACHEMENT
--------------------------------------------------------

  ALTER TABLE "TOPPATO"."T_ATTACHEMENT" ADD CONSTRAINT "PK_ATTACHEMENT" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "TOPPATO"."T_ATTACHEMENT" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "TOPPATO"."T_ATTACHEMENT" MODIFY ("STORY_ID" NOT NULL ENABLE);
  ALTER TABLE "TOPPATO"."T_ATTACHEMENT" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_PROJECT
--------------------------------------------------------

  ALTER TABLE "TOPPATO"."T_PROJECT" ADD CONSTRAINT "PK_PROJECT" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "TOPPATO"."T_PROJECT" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "TOPPATO"."T_PROJECT" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_STORY
--------------------------------------------------------

  ALTER TABLE "TOPPATO"."T_STORY" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "TOPPATO"."T_STORY" ADD CONSTRAINT "PK_STORY" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "TOPPATO"."T_STORY" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "TOPPATO"."T_STORY" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "TOPPATO"."T_STORY" MODIFY ("REPORTER_ID" NOT NULL ENABLE);
  ALTER TABLE "TOPPATO"."T_STORY" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_DAILYMEETING
--------------------------------------------------------

  ALTER TABLE "TOPPATO"."T_DAILYMEETING" ADD CONSTRAINT "PK_DAILYMEETING" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "TOPPATO"."T_DAILYMEETING" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "TOPPATO"."T_DAILYMEETING" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "TOPPATO"."T_DAILYMEETING" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_USER
--------------------------------------------------------

  ALTER TABLE "TOPPATO"."T_USER" ADD CONSTRAINT "PK_USER" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "TOPPATO"."T_USER" MODIFY ("ROLE" NOT NULL ENABLE);
  ALTER TABLE "TOPPATO"."T_USER" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "TOPPATO"."T_USER" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "TOPPATO"."T_USER" MODIFY ("LASTNAME" NOT NULL ENABLE);
  ALTER TABLE "TOPPATO"."T_USER" MODIFY ("FIRSTNAME" NOT NULL ENABLE);
  ALTER TABLE "TOPPATO"."T_USER" MODIFY ("TEAM_ID" NOT NULL ENABLE);
  ALTER TABLE "TOPPATO"."T_USER" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "TOPPATO"."T_USER" MODIFY ("PROJECT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_SPRINT
--------------------------------------------------------

  ALTER TABLE "TOPPATO"."T_SPRINT" ADD CONSTRAINT "PK_SPRINT" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "TOPPATO"."T_SPRINT" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "TOPPATO"."T_SPRINT" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "TOPPATO"."T_SPRINT" MODIFY ("REPORTER_ID" NOT NULL ENABLE);
  ALTER TABLE "TOPPATO"."T_SPRINT" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table T_REPORT
--------------------------------------------------------

  ALTER TABLE "TOPPATO"."T_REPORT" ADD CONSTRAINT "FK_REPORT_SPRINT" FOREIGN KEY ("SPRINT_ID")
	  REFERENCES "TOPPATO"."T_SPRINT" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_CHART
--------------------------------------------------------

  ALTER TABLE "TOPPATO"."T_CHART" ADD CONSTRAINT "FK_CHART_REPORT" FOREIGN KEY ("REPORT_ID")
	  REFERENCES "TOPPATO"."T_REPORT" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_ATTACHEMENT
--------------------------------------------------------

  ALTER TABLE "TOPPATO"."T_ATTACHEMENT" ADD CONSTRAINT "FK_ATTACHEMENT_STORY" FOREIGN KEY ("STORY_ID")
	  REFERENCES "TOPPATO"."T_STORY" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_STORY
--------------------------------------------------------

  ALTER TABLE "TOPPATO"."T_STORY" ADD CONSTRAINT "FK_STORY_ASSIGNED_USER" FOREIGN KEY ("ASSIGNED_USER_ID")
	  REFERENCES "TOPPATO"."T_USER" ("ID") ENABLE;
  ALTER TABLE "TOPPATO"."T_STORY" ADD CONSTRAINT "FK_STORY_BACKLOG" FOREIGN KEY ("BACKLOG_ID")
	  REFERENCES "TOPPATO"."T_BACKLOG" ("ID") ENABLE;
  ALTER TABLE "TOPPATO"."T_STORY" ADD CONSTRAINT "FK_STORY_REPORTER" FOREIGN KEY ("REPORTER_ID")
	  REFERENCES "TOPPATO"."T_USER" ("ID") ENABLE;
  ALTER TABLE "TOPPATO"."T_STORY" ADD CONSTRAINT "FK_STORY_SPRINT" FOREIGN KEY ("SPRINT_ID")
	  REFERENCES "TOPPATO"."T_SPRINT" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_USER
--------------------------------------------------------

  ALTER TABLE "TOPPATO"."T_USER" ADD CONSTRAINT "FK_USER_TEAM" FOREIGN KEY ("TEAM_ID")
	  REFERENCES "TOPPATO"."T_TEAM" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_SPRINT
--------------------------------------------------------

  ALTER TABLE "TOPPATO"."T_SPRINT" ADD CONSTRAINT "FK_SPRINT_PROJECT" FOREIGN KEY ("PROJECT_ID")
	  REFERENCES "TOPPATO"."T_PROJECT" ("ID") ENABLE;
  ALTER TABLE "TOPPATO"."T_SPRINT" ADD CONSTRAINT "FK_SPRINT_REPORTER" FOREIGN KEY ("REPORTER_ID")
	  REFERENCES "TOPPATO"."T_USER" ("ID") ENABLE;
